version: "3"
services:
 vampi-secure:
  build: .
  image: smithst987/vampi_docker:latest
  container_name: vampi-secure
  ports:
   - 5001:5000
  environment:
   - vulnerable=0

 vampi-vulnerable:
  build: .
  image: smithst987/vampi_docker:latest
  container_name: vampi-vulnerable
  ports:
   - 5002:5000
  environment:
   - vulnerable=1
