version: "3"
services:
 vampi-vulnerable:
  image: smithst987/vampi_docker:latest
  container_name: vampi-vulnerable
  build: .
  environment:  
    - CONTRAST__ENABLE=TRUE
    - CONTRAST__APPLICATION__NAME=VAmPI
    - CONTRAST__APPLICATION__GROUP=application_control_2
    - CONTRAST__APPLICATION__METADATA=bU=PS, contact=steve.smith@contrastsecurity.com
  ports:
   - 5002:5000
  environment:
   - vulnerable=1
