version: "3"
services:
 vampi-secure:
  image: vampi_docker:latest
  container_name: vampi-secure
  ports:
   - 5001:5001
  environment:
   - vulnerable=0

 vampi-vulnerable:
  image: vampi_docker:latest
  container_name: vampi-vulnerable
  ports:
   - 5002:5002
  environment:
   - vulnerable=1
